import Head from "next/head";
import Image from "next/image";
import Feed from "../components/Feed";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import { Uplodader } from "../components/Uploader";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import { BACKEND_URL } from "../const";

export default function Home() {
  const [uploaderOpen, setUploaderOpen] = useState(false);
  useEffect(() => {
    fetch(`${BACKEND_URL}/auth/posts`)
      .then((data) => {
        console.log(data);
      });
  }, []);

  const handleUpload = (e) => {
    console.log('handleUpload', e);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Cropify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar uploaderOpen={uploaderOpen} setUploaderOpen={setUploaderOpen} />
      <div className="flex flex-col md:flex-row">
        <Feed />
        <Sidebar />
        <Uplodader open={uploaderOpen} setUploaderOpen={setUploaderOpen} handleChange={handleUpload} />
      </div>
    </div>
  );
}
